name: GitHub Actions Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set Git config to allow long paths
      run: git config --global core.longpaths true

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test
